// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "HP7109";    // Network SSID (name)
const char PASS[]     = "Abhishek";    // Network password (use for WPA, or use as key for WEP)

void onLedStateChange();

bool ledState;

void initProperties(){

  ArduinoCloud.addProperty(ledState, READWRITE, ON_CHANGE, onLedStateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
